### ISSUE TITLE
GRID v1 Support

### ISSUE THREAD

**Issue by RoelGo** [akej74/grid-control#1]
I'm going to continue our conversation about the v1 support here.

So far the differences between the v1 and v2 seem to be the initialization response. 
This difference can however be used to detect what version of GRID is being used.
Could you maybe give me some advise about what would be best practice in Python for saving the version number as a variable.

Based on that variable I would be able to address the other differences which are the commands that involve voltage. 
Differences:
v2 0x8A fan#
v1 0x8A 0x00

v2 0x44 fan# 0xC0 0x00 0x00 voltage
v1 0x44 0x00 0xC0 0x00 0x00 voltage

The variable should also be used to changes some stuff in the UI.

**Comment by akej74** [comment]
Hi, I would recommend the following steps for adding Grid V1 support:
1. I'm using the UI itself as a data model, so all values, configuration parameters etc are read and updated directly to the QT widgets in the "GridControl" class.
2. Start by adding a "comboBox" widget somewhere in the UI with values "Grid V1" and "Grid V2. This UI element is then accessible everywhere in the "GridControl" class.
3. The method "init_communication" calls "grid.initialize_grid" with two arguments (the serial device and the "lock" needed for the serial communication). Here you could add another argument that reads the value from the UI directly, example:
   if grid.initialize_grid(self.ser, self.lock, self.ui.comboBoxGridType.currentText())
4.  self.ui.comboBoxGridType.currentText() just returns a string with the selected text, and you then need to add an extra argument in the initialize_grid function to use this for sending different initializing sequences depending on the Grid version.

I hope this makes sense, QT is a bit complex the first time you look at it :-) I also have a small "PyQT test" project on my GitHub that you could have a look at just to get a feeling of how it works. That project is also multithreaded so the same principle applies.

**Comment by akej74** [comment]
For managing the UI, you need QT Creator installed, which includes "Qt Designer" which is a nice UI editor (see README). QT Designer creates an XML file (ending in .ui) which is then converted to a Pyhon file (see doc string just below the GridControl class definition on how the command works). 

But I really recommend you try it out with PyQT-test first, to get a good understanding on how to setup/configure QT Creator using an existing .ui file.

**Comment by akej74** [comment]
Here are some good QT tutorials as well, helped me a lot when learning QT:
- http://zetcode.com/gui/pyqt5/
- http://www.tutorialspoint.com/pyqt/
- https://nikolak.com/pyqt-qt-designer-getting-started/
- http://projects.skylogic.ca/blog/how-to-install-pyqt5-and-build-your-first-gui-in-python-3-4/

**Comment by RoelGo** [comment]
Alright, thanks for all the information. You can track my progress on my profile.
I'm excited!

**Comment by akej74** [comment]
Closing this as it's really not an issue with Grid Control :-)
