### ISSUE TITLE
OHM as a part of install package

### ISSUE THREAD

**Issue by wiruzman** [akej74/grid-control#10]
Hi,

I think OpenHardwareMonitor should be a part of the install package.

It gives lesser complexity of running the application.

**Comment by akej74** [comment]
Hi, I like the idea, but if I bundle OHM, people will be using that version instead of newer versions made available from OHM (as OHM is currently in development and new releases are coming out). I prefer to ask people to grab the latest release from OHM and install separately.

**Comment by wiruzman** [comment]
That way you can control the version your application is using. You can
prevent your application is not crashing because something in the code has
changed after an user has updated OHM.

Think about it.

I didn't install the your application because I needed to install OHM as
well. I have already HwInfo, which is supported by many applications.

Regards,
Mehmet

Med venlig hilsen / Best regards
Mehmet Karahan

Den 17. feb. 2017 9.21 AM skrev "Åke Johansson" <notifications@github.com>:

**Comment by akej74** [comment]
Thanks for the update, the reason I'm using OHW is that is the only application I have found that exposes the actual sensor values to be used by other applications (this is done via WMI from OHM).

**Comment by wiruzman** [comment]
That is also fine, but you should consider to use specific version of OHM
due to updates which will crash your application. It is a seriously problem.

I'm also a software developer and making my software self contained.

2017-02-21 12:58 GMT+01:00 Åke Johansson <notifications@github.com>:

**Comment by akej74** [comment]
Yes, that is a good idea, let me add a disclaimer in the readme about which version of OHM works OK as a start.

**Comment by wiruzman** [comment]
That will be very nice as a start.

Med venlig hilsen / Best regards
Mehmet Karahan

Den 22. feb. 2017 9.32 AM skrev "Åke Johansson" <notifications@github.com>:

**Comment by akej74** [comment]
Readme updated with link to latest version of OHM beta (tested and works OK).
