### ISSUE TITLE
Grid Control

### ISSUE THREAD

**Issue by toksky** [akej74/grid-control#13]
on my 3840x2160 screen the GUI of the stand alone
is very small and some info over laps other info (very hard to read).Is there some way other than changing my resolution setting /to resize the GUI.
Thank you 
Toksky

**Comment by akej74** [comment]
Thanks for this info, I have only tested Grid Control on 1080p and 2k screens, where it works OK. Grid Control was my first project using QT and I must admit I was not aware of all features provided by the QT framwork, i.e. management of high DPI displays as described [here](http://doc.qt.io/qt-5/highdpi.html).

To make this fly, I believe a redesign of the UI is needed (using another setup of "layouts" in QT Designer) to make the UI resizeable. After this, some more work needs to be done according to the link provided above. 

I have limited time to work on this and I don't have access to a 4k monitor to test, so I believe I will not be able to work on these improvements myself right now. Maybe you could ask on r/NEXT on Reddit if there are someone that might be interested to pick this up and look into some improvements? 

Another alternative may be to bring this up with the author of [this project](https://github.com/kusti8/OpenHWControl), as he has integrated Grid Control in his application (besides a very nice implemetation for HUE+ control).

**Comment by toksky** [comment]
Thank you for your reply,and all that info/I am very grateful for your efforts with the Grid Control.
The Nzxt Cam software is a nightmare of bloatware,you have given people like me, who wish to use the 
Grid device, freedom for the NZXT dependency,I am forever thankful and can manage with the GUI.
I understand about the time it would take to rebuild the GUI,and it is probably not worth the effort,
the Grid Control works well and I am very PLEASED!!! I found the link that lead me to it.
Thank you
Toksky
PS.and I have great respect for your efforts and abilities

**Comment by akej74** [comment]
Closing for now as UI scaling requires a major redesign.
