### ISSUE TITLE
Not all temp sensors showing up.

### ISSUE THREAD

**Issue by WillPoulson** [akej74/grid-control#17]
Hi, so I've downloaded Grid Control and Open Hardware Monitor and it's all working fine. 

The issue I'm having with it is that I only have my 4th CPU core temp in the sensors tab when in Open Hardware Monitor I have all 4 of them available. Also the same thing with a few of the other sensors.

Any help?

**Comment by akej74** [comment]
Hi, interesting problem. Not sure what could be wrong, but maybe you can help with with a screenshot from OHM showing the sensors and a screenshot from Grid Control showing the missing one?

**Comment by WillPoulson** [comment]
Will do once I get home later today :)

**Comment by WillPoulson** [comment]
For now if it helps I remember that on the home screen of Grid Control there wasn't a status for OHM... However as I said in the temp sensor tab there were a few of them from OHM...

**Comment by WillPoulson** [comment]
Sorry for the very slow reply. When I got home and booted up, the issue seemed to have resolve itself so! All fixed!
