### ISSUE TITLE
Fan control resetting to manual on system startup

### ISSUE THREAD

**Issue by joleskins** [akej74/grid-control#18]
Hi, I recently set the fan mode to manual and shut my system down without changing it back to automatic. Now on every startup, the program uses manual mode. It simply won't save when I have it set to automatic and shut the system down. Is there a config file where I can manually save the setting? I'm not familiar with coding so I can't make anything out from the files in the folder. I'm using version 1.0.5 btw

**Comment by akej74** [comment]
Hi,

Grid Control automatically saves all settings when you exit the application by closing the window ("x" i the upper right corner). Please try to enable Automatic mode and then exit the application. Restart and verify if Automatic mode is enabled. Note that shutting down the system will not save the settings automatically.

If this doesn't work, you can check the saved settings in the registry as follows (one of the following locations, not sure which):

HKEY_CURRENT_USER\Software\GridControl\App\ 
HKEY_LOCAL_MACHINE\Software\GridControl\App\

Look for the variable "manual_control" which is either TRUE or FALSE.

**Comment by akej74** [comment]
The readme is now updated with information on how this works.

**Comment by joleskins** [comment]
Thank you, now it's saved as automatic. I didn't remember closing the program when I had set it to manual and shut down my system
