### ISSUE TITLE
Start the application minimized

### ISSUE THREAD

**Issue by ghost** [akej74/grid-control#19]
Hey man,

Thanks for creating this application. It is extremely helpful. I just have 1 request. Could you give the user the option to start the application minimized?
I'm trying to start this application minimized to the system tray when I log into windows 7. I tried creating a shortcut to the executable file, setting the shortcut's properties to start the executable minimized, and then putting the shortcut into the startup folder in the start menu. However that won't work b/c then the Grid Control application starts before the open Hardware Monitor application starts and gives me an error.
I then tried to use the Task Scheduler to start the Grid Control application when I log into windows with a 10 seconds delay and it worked. However, it won't start the application minimized b/c the Task Scheduler can't launch the shortcut, only the executable file directly.
I also tried to use a batch file, but that didn't work either.
Your application already minimizes to the tray, which is awesome. I just need it to minimize at startup

Otherwise, this application is perfect!!!

Thanks

**Comment by akej74** [comment]
Hi, this is a good idea, please find a new release (1.0.6) with this feature implemented. It's a checkbox and if enabled, Grid Control will start minimized (tray icon visible).

Please try it out and let me know how it works. Note that the "Start minimized" setting is saved when you exit the application (as all other settings as well).

**Comment by ghost** [comment]
It worked perfectly!!!
Thank you so much for the quick reply and fix.
You put the NZXT devs to shame. 
Keep up the good work!!!

P.S.
While the application works perfectly as it is now, I have 3 more issues (1 request, 1 suggestion, 1 inquiry) that I'd like to share with you to make this application even better. So, I'll open an issue for each one

**Comment by akej74** [comment]
Great, closing this issue.
