### ISSUE TITLE
Simulated temperatures should be disabled for Manual control 

### ISSUE THREAD

**Issue by ghost** [akej74/grid-control#20]
Hi there,
Just a quick recommendation to enhance the aesthetics of the application. Under the General tab, if the user chooses the Manual option in the Fan control section, then the entire Simulate temperatures box should be greyed out. This would better convey to the user that this box really only has any meaning when the Fan control is set to Automatic (after all, what's the point of artificially changing the CPU and GPU's temps if, under Manual control, the fans are not affected by it)

Thanks for listening

**Comment by akej74** [comment]
Good idea, added to my todo list for next version.

**Comment by akej74** [comment]
Fixed in 1.0.8, please try it out.

**Comment by ghost** [comment]
Works perfectly. Nicely done!!!

**Comment by akej74** [comment]
Thanks, closing.
