### ISSUE TITLE
Add minimize location choice

### ISSUE THREAD

**Issue by ghost** [akej74/grid-control#23]
Hi there,

Just another quick suggestion to improve the flexibility of this application. While I don't personally need this function, some users might appreciate having the choice to minimize the app either to the system tray (by default) or to the Taskbar. Do you think you could implement something like that?

Thanks!!!

**Comment by akej74** [comment]
Also a good idea, added to to-do list.

**Comment by akej74** [comment]
Fixed in 1.0.8, please try it out (new checkbox).

**Comment by ghost** [comment]
Works perfectly. Nicely done!!!

**Comment by akej74** [comment]
Thanks, closing.
