### ISSUE TITLE
Fans spinning up and down non-stop.

### ISSUE THREAD

**Issue by Anreill** [akej74/grid-control#26]
My fans (5, 3 NZXT AER, 2 randoms) are spinning up and down constantly. The NZXT fans will run up to 1680-1700rpm, the off ones will bump up to 6-800rpm, then they'll drop back to about 1200(AER)/500(generic) before going back up. 

This basically just repeats over and over. If I put a little load on they seem to behave somewhat better, going up to a percentage speed instead of maxing out, but they still stop and start.

While this is happening the status indicators in Grid Control are flipping from green to red over and over as well.

All fans are set to read CPU temp. 

Polling every 500ms.

CPU Temp as I'm typing this is fluctuating from 32-34C depending on the pulsing of the fans.

30% min speed. (This doesn't seem to matter? If I set the temp to start increasing higher than the current temp, the fans just stop completely.)
Increase at 30C.
Intermediate is 70% @ 60C.
100% at 75C+.

I'd love to get this to work properly, as CAM is a buggy piece of junk.

Thanks.

**Comment by akej74** [comment]
Hi, the Grid unit will automatically push out max voltage for a few seconds if it believes a fan has stopped. I would recommend that you change the min speed to 50% for all fans and see how this works out. If that is OK, try with 45% etc. 

The manual mode of Grid Control may be useful as well for testing the fan behavior at different voltages/speed.

**Comment by Anreill** [comment]
I experimented a bit more and set it to start scaling at 1C, fans seem to be running properly.

Except now I get this every time I try to launch it. No changes made to Grid Control. Machine was on all day and it was running fine, started doing this after updating Kusti8's Hue Plus and rebooting.

![image](https://user-images.githubusercontent.com/38512672/39024027-e09cdf3a-4403-11e8-92da-1a29090e175b.png)

**Comment by akej74** [comment]
Well, something is locking port COM4, most likely Hue Plus as you said it was updated. Maybe Hue Plus is using the same port?
