### ISSUE TITLE
Grid control no longer sees the Grid+ V2

### ISSUE THREAD

**Issue by aebange** [akej74/grid-control#34]
Just started today, suddenly unable to connect to the serial port on the Grid+ V2. Found an old image I took a few months back when I got it working - [it appears to have been connecting to COM3](https://i.imgur.com/eWmqjrY.png). But now COM3 [is not available as an option](https://i.imgur.com/eji3gY0.png) and when I try to connect to COM1 (the only option) [it throws a 0x20 error](https://i.imgur.com/svXQbQA.png). 

I have unplugged/replugged the USB connection from the board and the unit several times seeing no changes in behavior. I've rebooted the desktop several times as well.

The fans still are operating at the default speeds set by the Grid+ and power down when the USB/Grid+ power is removed. I'm just completely unable to control them from the software. The USB port seems to be functioning properly as well.

I really hope this isn't a hardware issue with the Grid+, it will have been the 3rd NZXT accessory I purchased that broke after only several months. They make nice cases but their other products are trash.

**Comment by aebange** [comment]
I've narrowed it down a bit. Despite the fact that the COM3 (USB) pins on the motherboard appear to be supplying some sort of signal to the Grid+ (when unplugged from this, all fans go 100% off), it is not recognized as plugged in by windows. So clearly there is an issue preventing windows/gridcontrol from recognizing that the Grid+ is actually connected to COM3

**Comment by aebange** [comment]
Aaand I have just "Solved" the problem. For no explainable reason, my FUSB_1 port on my motherboard is no longer able to send/receive information but is still able to provide a charge. By swapping the Grid+ USB connection with my cases USB 2.0 connector, I have restored function. However this has raised a new question - has the Grid+ damaged my motherboard? I am going to contact my MB's manufacturer to find a solution to this problem.

**Comment by akej74** [comment]
Great that the problem was resolved, I hope your MB is OK.
