### ISSUE TITLE
Open Hardware Monitor Connection

### ISSUE THREAD

**Issue by kiltedpiper** [akej74/grid-control#8]
Hi! Thank you for this, I was having the CAM game crashing issues. I am not able to get the Grid-Control to connect to Open Hardware, the status is 3 red lines. I have tried starting OHM first and second, and have them both set to run as Admin mode. Do they need to be in the same folder or anything like that?  Thanks!!

**Comment by kiltedpiper** [comment]
Well, figured that one out :)  I needed to assign the CPU and GPU monitor set up in the sensors, then it worked.

**Comment by akej74** [comment]
Thanks for your comment, maybe I should add some info about that in the application, or change the logic to make it more user friendly.

**Comment by oje011** [comment]
You should specify that you are checking for that exact OpenHardwareMonitor version.
I tried using the existing one I had, but it didn't show up anywhere. It worked when using the version you linked to. 

Thanks for an awesome tool. Really loving the config and the lightweight operation.

**Comment by akej74** [comment]
Updated Readme as follows:
* Info that you need to configure sensors; before that is done you will get the "Check that OHM is running" warning message
* Added link to latest OHM beta (tested and works OK)
